name: bottom_up
channels:
  - pytorch
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - anaconda=2021.11
  - anaconda-client=1.9.0
  - anaconda-navigator=2.1.1
  - anaconda-project=0.10.1
  - anyio=2.2.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astroid=2.6.6
  - astropy=4.3.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.0
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - blosc=1.21.0
  - bokeh=2.4.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.11.0
  - conda-build=3.21.5
  - conda-content-trust=0.1.1
  - conda-env=2.6.0
  - conda-pack=0.6.0
  - conda-package-handling=1.7.3
  - conda-repo-cli=1.0.4
  - conda-token=0.3.0
  - conda-verify=3.4.2
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - curl=7.78.0
  - cycler=0.10.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - daal4py=2021.3.0
  - dal=2021.3.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docutils=0.17.1
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - expat=2.4.1
  - fastcache=1.1.0
  - ffmpeg=4.3
  - flake8=3.9.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - gnutls=3.6.15
  - graphite2=1.3.14
  - greenlet=1.1.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.3.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.2
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jeepney=0.7.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.1.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcurl=7.78.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblief=0.10.1
  - libllvm11=11.1.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.37.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.10.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.5
  - numba=0.54.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - pango=1.45.3
  - parso=0.8.2
  - partd=1.2.0
  - patchelf=0.13
  - path=16.0.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - pkginfo=1.7.1
  - pluggy=0.13.1
  - ply=3.11
  - poyo=0.5.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyodbc=4.0.31
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=22.2.1
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - requests=2.26.0
  - ripgrep=12.1.1
  - rope=0.19.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.3.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.2.1
  - sphinx=4.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - sympy=1.9
  - tbb=2021.4.0
  - tbb4py=2021.4.0
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - urllib3=1.26.7
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.0
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.1.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.1
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - absl-py==1.3.0
    - accelerate==0.18.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - altair==4.2.0
    - async-timeout==4.0.2
    - backoff==2.2.1
    - backports-csv==1.0.7
    - base58==2.1.1
    - blinker==1.5
    - blis==0.4.1
    - boto3==1.21.11
    - botocore==1.24.11
    - cached-path==1.0.2
    - cachetools==5.0.0
    - catalogue==1.0.0
    - checklist==0.0.11
    - cheroot==8.6.0
    - cherrypy==18.6.1
    - commonmark==0.9.1
    - conllu==4.4.1
    - cymem==2.0.6
    - datasets==2.7.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - editdistance==0.6.0
    - en-core-web-sm==3.2.0
    - fairscale==0.4.5
    - feedparser==6.0.8
    - filelock==3.4.2
    - flask-cors==3.0.10
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - fuzzywuzzy==0.18.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-api-core==2.5.0
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.2.2
    - google-cloud-storage==1.44.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.3.0
    - googleapis-common-protos==1.55.0
    - grpcio==1.51.1
    - huggingface-hub==0.11.1
    - iso-639==0.4.5
    - isodate==0.6.1
    - jaraco-classes==3.2.1
    - jaraco-collections==3.5.1
    - jaraco-context==4.1.1
    - jaraco-functools==3.5.0
    - jaraco-text==3.7.0
    - jmespath==0.10.0
    - jsonnet==0.18.0
    - jsonpickle==2.1.0
    - langcodes==3.3.0
    - lmdb==1.3.0
    - markdown==3.4.1
    - multidict==6.0.3
    - multiprocess==0.70.14
    - munch==2.5.0
    - murmurhash==1.0.6
    - networkx==2.4
    - oauthlib==3.2.2
    - openai==0.27.7
    - overrides==3.1.0
    - pandas-stubs==1.5.1.221024
    - parsimonious==0.8.1
    - pathlib==1.0.1
    - pathtools==0.1.2
    - pathy==0.6.1
    - patternfork-nosql==3.6
    - pdfminer-six==20211012
    - plac==1.1.3
    - portend==3.1.0
    - preshed==3.0.6
    - promise==2.3
    - protobuf==3.19.4
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pydeck==0.8.0
    - pydeprecate==0.3.1
    - pympler==1.0.1
    - python-docx==0.8.11
    - pytorch-lightning==1.5.10
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz-deprecation-shim==0.1.0.post0
    - rank-bm25==0.2.2
    - rdflib==6.1.1
    - regex==2023.5.5
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rich==12.6.0
    - rsa==4.8
    - s3transfer==0.5.2
    - sacremoses==0.0.47
    - semver==2.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.96
    - sentry-sdk==1.5.6
    - seqeval==1.2.2
    - setproctitle==1.2.2
    - setuptools==59.5.0
    - sgmllib3k==1.0.0
    - shortuuid==1.0.8
    - simplet5==0.1.4
    - simpletransformers==0.63.9
    - smart-open==5.2.1
    - smmap==5.0.0
    - spacy==2.2.4
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.1
    - sparqlwrapper==1.8.5
    - sqlparse==0.4.2
    - srsly==1.0.5
    - stanfordnlp==0.2.0
    - streamlit==1.12.0
    - tempora==5.0.1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - termcolor==1.1.0
    - thinc==7.4.0
    - tiktoken==0.4.0
    - tokenizers==0.13.3
    - torchmetrics==0.11.0
    - transformers==4.28.1
    - typer==0.4.0
    - types-pytz==2022.6.0.1
    - tzdata==2022.7
    - tzlocal==4.2
    - validators==0.20.0
    - wandb==0.12.11
    - wasabi==0.9.0
    - word2number==1.1
    - xxhash==3.1.0
    - yarl==1.8.2
    - yaspin==2.1.0
    - zc-lockfile==2.0
prefix: [path_to_your_conda_env]
